### PR TITLE
Add updatePagingState to pagingController with copyWith

### PR DESCRIPTION
**Pull request by SHRJamal**
I added copyWith to PagingState class, and updatePagingState to pagingController. the current solution of changing directly .value is not good, copyWith made it much simpler: 
```
pagingController.updatePagingState(
    (v) => v.copyWith(
         itemList: v.itemList..removeWhere((u) => u.id == userId),
    ),
);
```

### CODE REVIEW

**Comment by EdsonBueno** [comment]
Hi @SHRJamal, I appreciate your efforts.
Can you elaborate more on why changing `value` directly is not good? That's exactly how Flutter's `TextEditingController` and all other `ValueNotifier`s work. It's a pattern well known in the Flutter community.

As for the `copyWith`, that doesn't have to be responsibility of the package. You can create it as a Dart extension in your project. You ended up adding another external dependency to the package which is not good at all.

**Comment by SHRJamal** [comment]
Using `value` you will need add all the fields of pagingState. if you forget to add nextPageKey for example, something wrong will happen.
 ```
pagingController.value = PagingState(
      itemList: newItemList,
      error: pagingController.error,
      nextPageKey: pagingController.nextPageKey,
    );
```

about `copyWith` it not external package it just method added to PagingState class

**Comment by EdsonBueno** [comment]
You can solve the fact of having to add all fields by creating an extension on your side.
The package I'm talking about is `equatable` (which your PR adds).

**Comment by SHRJamal** [comment]
`equatable` is just for implementing of == and toString on your models. and you can remove it.
that was just simple improvement suggested.
anyway thanks.

**Pull request closed without merging**
