### PR TITLE
Optimize PagingController for better performance and readability

### PR DESCRIPTION
**Pull request by fjyeo**
- Update ObserverList declarations to be non-nullable
- Refactor appendPage method using spread operator
- Simplify _debugAssertNotDisposed check
- Use clear() instead of null assignment in dispose method

### CODE REVIEW

**Comment by AdamTechAcc** [comment]
@fjyeo, what is a performance improvement?

**Comment by fjyeo** [comment]
Most of these changes aid performances for example the clearing will have a small benefit

**Comment by clragon** [comment]
Thank you for your PR. 
The controller structure in the upcoming version 5 of this package has changed significantly and these changes do unfortunately no longer apply.

**Comment by fjyeo** [comment]
Okay. No problem!

**Pull request closed without merging**
